---
version: "3.8"

services:

  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run --config /config/adguardhome-sync.yaml
    networks:
      - frontend

    volumes:
      - /opt/appdata/adguardhome-sync/adguardhome-sync.yaml:/config/adguardhome-sync.yaml

    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    networks:
      - backend
      - frontend
    volumes:
      - /opt/appdata/homarr/configs:/app/data/configs
      - /opt/appdata/homarr/icons:/app/public/icons
      - /opt/appdata/homarr/data:/data


  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    networks: 
      - frontend
      - backend
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /opt/appdata/Nginx-Proxy-Manager/data:/data
      - /opt/appdata/Nginx-Proxy-Manager/letsencrypt:/etc/letsencrypt

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/Syncthing/config:/config
      - Syncthing:/data
    networks: 
      - frontend
      - backend
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

volumes:
  Syncthing:
    name: Syncthing
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/syncthing
    
networks:
    frontend:
      name: frontend
    backend:
      name: backend
      internal: true
