---
version: "3.8"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=jellyfin.casa.tomasgalvao.me #optional
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - Metadata:/config
      - Media:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/sonarr:/config
      - Media_Data:/data
    restart: unless-stopped

  sonarrAni:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarrAni
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/sonarrAni:/config
      - Media_Data:/data
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/radarr:/config
      - Media_Data:/data
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8081
      - DOCKER_MODS=marzzzello/linuxserver-io-mod-qbit-matui|arafatamim/linuxserver-io-mod-vuetorrent
    volumes:
      - /opt/appdata/qbittorrent:/config
      - Downloads_Torrent:/data/Downloads/Torrent/
    ports:
      - 8081:8081
      - 40202:40202
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/bazarr:/config
      - Media_Data:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - backend
      - media
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/prowlarr:/config
    restart: unless-stopped
    
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    ports:
      - 5454:5454
    networks:
     - media
     - backend
    volumes:
      - /opt/appdata/notifiarr:/config
      - /var/run/utmp:/var/run/utmp

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - media
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    restart: unless-stopped 

  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    networks:
      - media
      - backend
    volumes:
      - /opt/appdata/wizarr/database:/data/database
  
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - media
      - backend
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
    volumes:
      - /opt/appdata/jellyseerr/config:/app/config
    restart: unless-stopped

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    networks:
      - media
      - backend
    environment:
      - TZ=Europe/London
    volumes:
      - /opt/appdata/autobrr/config:/config

 # cross-seed:
 #   image: ghcr.io/cross-seed/cross-seed
 #   container_name: cross-seed
 #   networks:
 #     - media
 #   volumes:
 #     - /opt/appdata/cross-seed:/config
 #     - /opt/appdata/qbittorrent/qBittorrent/BT_backup:/torrents:ro # your torrent clients .torrent cache, can and should be mounted read-only (e.g. qbit: `BT_Backup` | deluge: `state` | transmission: `transmission/torrents` | rtorrent: session dir from `.rtorrent.rc`)
 #     - Torrent_Watch:/cross-seeds
 #   command: search # this enables the search mode, change to daemon to specifically run the daemon

volumes:

  Downloads_rTorrent:
    name: Downloads_rTorrent
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data/Downloads/rTorrent

  Downloads_Torrent:
    name: Downloads_Torrent
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data/Downloads/Torrent

  Torrent_Watch:
    name: Torrent_Watch
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data/Downloads/Torrent/WATCH
      
  Media_Data:
    name: Media_Data
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data
    
  Metadata:
    name: Plex_Metadata
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/media_metadata
    
  Media:
    name: Media
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data/Media

networks:
    media:
      name: media
    backend:
      external: true
      name: backend
