---
version: "3.8"

services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=jellyfin.casa.tomasgalvao.me #optional
    volumes:
      - Metadata:/config
      - Media:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

#  plex:
#    image: lscr.io/linuxserver/plex:latest
#    container_name: plex
#    networks:
#      - backend
#      - media
#    ports:
#      - 32400:32400/tcp
#      - 3005:3005/tcp
#      - 8324:8324/tcp
#      - 32469:32469/tcp
#      - 1900:1900/udp
#      - 32410:32410/udp
#      - 32412:32412/udp
#      - 32413:32413/udp
#      - 32414:32414/udp
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#      - VERSION=docker
#      - PLEX_CLAIM=claim-yP9zBnziE3zfeYuZV3ca
#    volumes:
#      - Plex_Metadata:/config
#      - Plex_Media:/media
#
#    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/sonarr:/config
      - Media_Data:/data
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/radarr:/config
      - Media_Data:/data
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/sabnzbd:/config
      - Downloads_NZB:/data/Downloads/Nzb/

    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /opt/appdata/qbittorrent:/config
      - Downloads_Torrent:/data/Downloads/Torrent/
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - backend
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/bazarr:/config
      - Media_Data:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - backend
      - media
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/appdata/prowlarr:/config
    restart: unless-stopped
    
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    ports:
      - 5454:5454
    networks:
     - media
     - backend
    volumes:
      - /opt/appdata/notifiarr:/config
      - /var/run/utmp:/var/run/utmp

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - media
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    restart: unless-stopped 
  

volumes:

  Downloads_NZB:
    name: Downloads_NZB
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data/Downloads/Nzb

  Downloads_Torrent:
    name: Downloads_Torrent
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data/Downloads/Torrent
      
  Media_Data:
    name: Media_Data
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data
    
  Metadata:
    name: Plex_Metadata
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/media_metadata
    
  Media:
    name: Media
    driver_opts:
      type: nfs
      o: 	addr=192.168.0.6,rw,nfsvers=4
      device: :/mnt/user/data/Media

networks:
    media:
      name: media
    backend:
      external: true
      name: backend
